import Link from "next/link";
import { Brain } from "lucide-react";

export const metadata = { title: "Terms of Service · StudyOS" };

export default function TermsPage() {
  return (
    <div className="mx-auto max-w-2xl px-6 py-16">
      <Link href="/" className="mb-8 flex items-center gap-2">
        <div className="flex h-7 w-7 items-center justify-center rounded-md bg-brand-500">
          <Brain size={14} className="text-white" />
        </div>
        <span className="font-display text-sm font-bold text-gray-900">StudyOS</span>
      </Link>

      <h1 className="font-display text-2xl font-bold text-gray-900">Terms of Service</h1>
      <p className="mt-2 text-sm text-gray-400">Last updated {new Date().getFullYear()}</p>

      <div className="mt-8 space-y-6 text-sm leading-relaxed text-gray-600">
        <p>
          By using StudyOS you agree to use the platform for personal, educational
          purposes only. Content generated by StudyOS (notes, MCQs, numericals, and
          tutor responses) is AI-generated and may contain errors — always verify
          against your official course material before an exam.
        </p>
        <p>
          You are responsible for the content you upload. Do not upload material you
          do not have the right to use for personal study purposes.
        </p>
        <p>
          StudyOS is provided &quot;as is&quot; without warranty of any kind. We are
          not liable for exam outcomes based on generated study material.
        </p>
        <p>
          We may update these terms as the product evolves; continued use after an
          update constitutes acceptance of the revised terms.
        </p>
        <p className="text-gray-400">
          This is a placeholder terms document for the StudyOS project and should be
          replaced with a reviewed legal document before production use.
        </p>
      </div>
    </div>
  );
}
